# Generated by Django 3.2.14 on 2023-02-28 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0068_alter_productsize_name_variation'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='product_type',
            field=models.CharField(blank=True, choices=[('New', 'New'), ('Old', 'Old'), ('Service', 'Service')], default='New', max_length=13, null=True),
        ),
    ]
